# This workflow will run packages tests using a variety of Python versions.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.13"]
        python-requirements: ["test_requirements.txt", "test_requirements_flask_2.txt"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.python-requirements }}
    - name: Test with pytest
      run: |
        pytest
